### ISSUE TITLE
Module not found: Can't resolve '@walletconnect/client'

### ISSUE THREAD

**Issue by zxlvera** [Web3Auth/web3auth-pnp-examples#128]
### **Describe the bug**
Got `@walletconnect` related errors when attempting to run repo.
`Module not found: Can't resolve '@walletconnect/client'`

`yarn add @web3auth/wallet-connect-v1-adapter` or
`yarn add @web3auth/wallet-connect-v2-adapter` does not work

### **To Reproduce**

1. Go to [web-modal-sdk-evm](https://github.com/Web3Auth/web3auth-pnp-examples/tree/main/web-modal-sdk/evm)
2. Clone either of these folders: `nextjs`, `react-evm-modal-example`, `react-vite-evm-modal-example`
3. `yarn install`, `yarn dev`

### **Expected behavior**

A page with web3auth login should appear

### **Screenshots**

<img width="937" alt="image" src="https://user-images.githubusercontent.com/17290983/231499871-15165925-4564-4d15-8df4-303d8e95dd02.png">

### **Device Info (please complete the following information):**

- Device: Macbook Pro M1
- OS: MacOS Ventura
- Browser chrome
- Web3Auth Version [e.g. 1.0.0]

### **Additional context**

> WalletConnect's v1 SDKs are now deprecated. Please upgrade to a v2 SDK. For details see: https://docs.walletconnect.com/

Can anyone support walletconnect with `yarn`

**Comment by zxlvera** [comment]
Workaround: install with `npm`
https://github.com/orgs/Web3Auth/discussions/1359

**Comment by Graciela985** [comment]
It's an issue with some wallets apparently.I had a similar issue. I contacted metamask/binance directly and they had it resolved for me. alarcongraciela985@gmail.com
Send them a mail. They'll help you out.

**Comment by shahbaz17** [comment]
Hey @zxlvera 

Thank you for raising the issue, and glad to hear it works with npm.
