### ISSUE TITLE
There seems to be some bug in the code. please contact support to fix this.Missing state params

### ISSUE THREAD

**Issue by divyesh-frodobots** [Web3Auth/web3auth-pnp-examples#145]
We get this error on one of the user , any idea why that user got this error , for other user it's working fine 

`Error` ``There seems to be some bug in the code. please contact support to fix this.Missing state params #145``

![image (1)](https://user-images.githubusercontent.com/125444846/236738666-7b4664fc-ea1b-48cc-b460-143cbdf6de8c.png)

**Comment by shahbaz17** [comment]
Hey @divyesh-frodobots 

In which example you got this error?

**Comment by shahbaz17** [comment]
For any further questions, please follow up on https://community.web3auth.io/

Thank you!
