### ISSUE TITLE
Error while executing web3auth-safe-example

### ISSUE THREAD

**Issue by devrajsinghrawat** [Web3Auth/web3auth-pnp-examples#156]
### **Describe the bug**

This Error occurs in AA x Safe Example , After User logs in using Social login like Gmail. It shows 

**No Available Safes, Please create one by clicking the above button.**

When the button is clicked the below error occurs.

```
ERROR
Internal JSON-RPC error.
    at getEthJsonRpcError (http://localhost:3000/static/js/bundle.js:94551:10)
    at Object.internal (http://localhost:3000/static/js/bundle.js:94455:22)
    at provider.sendAsync (http://localhost:3000/static/js/bundle.js:47484:71)
    at async provider.request (http://localhost:3000/static/js/bundle.js:47506:17)
```

### **To Reproduce**

1. clone repo from https://github.com/Web3Auth/web3auth-pnp-examples
2. go to **web3auth-pnp-examples/account-abstraction/web3auth-safe-example**
3. install all dependencies and run command npm start
4. go to http://localhost:3000/
5. Click login and select Gmail as social login method
6. Click on Create Safe

### **Expected behavior**

Not sure but this should have navigated to Safe Creation Page 

### **Screenshots**
![image](https://github.com/Web3Auth/web3auth-pnp-examples/assets/44597990/756309b9-da65-4fba-b66c-c2cd672ae331)

### **Device Info (please complete the following information):**

- Device:  Laptop
- OS: Win 11
- Browser: Chrome, Mozila
- Web3Auth Version: Nothing changed in Package Json after cloning

**Comment by shahbaz17** [comment]
Hey @devrajsinghrawat 

Please try passing your custom Goerli RPC url from services like QuickNode, Infura, Alchemy etc.. to this line -> https://github.com/Web3Auth/web3auth-pnp-examples/blob/main/account-abstraction/web3auth-safe-example/src/App.tsx#L38

**Comment by shahbaz17** [comment]
For any further questions, please follow up on https://community.web3auth.io/

Thank you!
