### ISSUE TITLE
firebase X Github doesn't work in Web3Auth/web3auth-pnp-examples/web-no-modal-sdk/custom-authentication/aggregate-verifiers/firebase-google-aggregate-react-no-modal-example

### ISSUE THREAD

**Issue by JWMatheo** [Web3Auth/web3auth-pnp-examples#355]
### **Describe the bug**

When push the `login using Github [ via Firebase ]` button i got `There seems to be some bug in the code. Please contact support to fix this. Invalid params`

### **To Reproduce**

This is the exact same step as described here : web-no-modal-sdk/custom-authentication/aggregate-verifiers/firebase-google-aggregate-react-no-modal-example

Download Manually

```bash
npx degit Web3Auth/web3auth-pnp-examples/web-no-modal-sdk/custom-authentication/aggregate-verifiers/firebase-google-aggregate-react-no-modal-example w3a-nomodal-aggregate-firebase
```

Install & Run:

```bash
cd w3a-nomodal-aggregate-firebase
npm install
npm run start
# or
cd w3a-nomodal-aggregate-firebase
yarn
yarn start
```

Then push the `login using Github [ via Firebase ]` button and wait

### **Expected behavior**

Should instanciate the web3auth.connectTo

### **Screenshots**

![image](https://github.com/Web3Auth/web3auth-pnp-examples/assets/88055282/216e8064-daa3-48c5-99b2-73214575457e)
![image](https://github.com/Web3Auth/web3auth-pnp-examples/assets/88055282/385dc422-6599-4ddd-9abf-cce1c400f65d)

It fails at the line 140.

**Comment by yashovardhan** [comment]
Please ask your questions on https://community.web3auth.io
